 on:
   push:
     branches:
       - master




  
 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: "Login to Docker Hup"
         run: docker login --username hasnaaebrahim--password dckr_pat_edLCve5Jte1nPxONkz5sXUlGNPc


       - name: "Bulding docker image"
         run: docker build -t  hasnaaebrahim/myimage       

       - name: "Pushing to Docker Hup"
         run: docker push  hasnaaebrahim/myimage 